spring:
  application:
    name: blog
  datasource:
    url: jdbc:h2:mem:dbtest
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

#  flyway:
#    baseline-on-migrate: true
#    enabled: true
#    locations: classpath:db/migration


my:
  blog:
    secretKey: mysecret
    tokenExpired: 86400000

logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG
